package cmd

import (
	"log"
	"os"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/swagger"
	"github.com/spf13/cobra"
	_ "github.com/vanpelt/catnip/docs" // This will be generated by swag
	"github.com/vanpelt/catnip/internal/config"
	"github.com/vanpelt/catnip/internal/handlers"
	"github.com/vanpelt/catnip/internal/models"
	"github.com/vanpelt/catnip/internal/services"
)

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "🚀 Start the Catnip server",
	Long: `Start the Catnip HTTP/WebSocket server.

This command starts the main Catnip server that provides:
- 🖥️  Web interface for container management
- 🔌 WebSocket PTY sessions for terminal access
- 📊 Real-time port monitoring and proxying
- 📁 Git repository and worktree management
- 🤖 Claude AI integration for development assistance

The server will automatically detect and proxy to running services on different ports.`,
	Run: func(cmd *cobra.Command, args []string) {
		startServer(cmd)
	},
}

func init() {
	rootCmd.AddCommand(serveCmd)

	// Add port flag
	serveCmd.Flags().StringP("port", "p", "8080", "Port to listen on")
}

// @title Catnip Container API
// @version 1.0
// @description API for managing container PTY sessions and services
// @host localhost:8080
// @schemes http ws
func startServer(cmd *cobra.Command) {
	// Import and log runtime configuration
	log.Printf("🚀 Starting Catnip in %s mode", config.Runtime.Mode)
	if config.Runtime.IsNative() {
		log.Printf("📁 Workspace: %s", config.Runtime.WorkspaceDir)
		log.Printf("⚙️  Config: %s", config.Runtime.VolumeDir)
		if config.Runtime.CurrentRepo != "" {
			log.Printf("📦 Current repo: %s", config.Runtime.CurrentRepo)
		}
	}

	// Start settings persistence manager in containerized environments
	var settings *models.Settings
	if config.Runtime.IsContainerized() {
		settings = models.NewSettings()
		settings.Start()
		defer settings.Stop()
	}

	// Initialize Git service (but don't defer Stop() yet, as we need to set up dependencies first)
	gitService := services.NewGitService()
	defer gitService.Stop()

	// Initialize Git HTTP service
	gitHTTPService := services.NewGitHTTPService(gitService)

	// Initialize port monitoring service
	portMonitor := services.NewPortMonitor()
	defer portMonitor.Stop()

	// Check CATNIP_REPO environment variable
	if catnipRepo := os.Getenv("CATNIP_REPO"); catnipRepo != "" {
		log.Printf("🌟 CATNIP_REPO detected: %s", catnipRepo)
		go func() {
			// Parse CATNIP_REPO format: github.com/owner/repo[@branch]
			parts := strings.Split(catnipRepo, "@")
			repoParts := strings.Split(strings.TrimPrefix(parts[0], "github.com/"), "/")
			if len(repoParts) >= 2 {
				org := repoParts[0]
				repo := strings.Join(repoParts[1:], "/")
				branch := ""
				if len(parts) > 1 {
					branch = parts[1]
				}

				log.Printf("📦 Auto-checkout: %s/%s (branch: %s)", org, repo, branch)
				if _, _, err := gitService.CheckoutRepository(org, repo, branch); err != nil {
					log.Printf("❌ Failed to checkout repository: %v", err)
				}
			}
		}()
	}

	app := fiber.New(fiber.Config{
		DisableStartupMessage: false,
		AppName:               "Catnip Container v1.0.0",
	})

	// Middleware
	app.Use(handlers.SamplingLogger())
	app.Use(recover.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "Origin, Content-Type, Accept",
	}))

	// Health check
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok"})
	})

	// Settings endpoint - returns environment configuration
	app.Get("/v1/settings", func(c *fiber.Ctx) error {
		catnipProxy := os.Getenv("CATNIP_PROXY")
		return c.JSON(fiber.Map{
			"catnipProxy":  catnipProxy,
			"authRequired": catnipProxy != "",
		})
	})

	// Swagger documentation
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Register Git HTTP routes (must be before other routes to catch .git URLs)
	gitHTTPService.RegisterRoutes(app)

	// API v1 routes
	v1 := app.Group("/v1")

	// Initialize services
	claudeService := services.NewClaudeService()
	sessionService := services.NewSessionService()

	// Initialize and start Claude monitor service
	claudeMonitor := services.NewClaudeMonitorService(gitService, sessionService, claudeService)

	// Initialize handlers
	ptyHandler := handlers.NewPTYHandler(gitService, claudeMonitor, sessionService)

	// Wire up the setup executor to enable setup.sh execution in new worktrees
	log.Printf("🔧 Setting up setupExecutor for gitService")
	gitService.SetSetupExecutor(ptyHandler)
	log.Printf("✅ setupExecutor configured successfully")

	// Wire up the claude monitor to git service
	gitService.SetClaudeMonitor(claudeMonitor)

	// Now initialize local repositories with setup executor properly configured
	gitService.InitializeLocalRepos()
	if err := claudeMonitor.Start(); err != nil {
		log.Printf("⚠️  Failed to start Claude monitor service: %v", err)
	} else {
		log.Printf("✅ Claude monitor service started successfully")
	}
	defer claudeMonitor.Stop()

	authHandler := handlers.NewAuthHandler()
	uploadHandler := handlers.NewUploadHandler()
	gitHandler := handlers.NewGitHandler(gitService, gitHTTPService, sessionService, claudeMonitor)
	claudeHandler := handlers.NewClaudeHandler(claudeService)
	sessionHandler := handlers.NewSessionsHandler(sessionService, claudeService)
	portsHandler := handlers.NewPortsHandler(portMonitor)
	proxyHandler := handlers.NewProxyHandler(portMonitor)
	eventsHandler := handlers.NewEventsHandler(portMonitor, gitService)
	defer eventsHandler.Stop()

	// Connect events handler to GitService for worktree status events
	gitService.SetEventsHandler(eventsHandler)
	log.Printf("✅ EventsHandler connected to GitService for worktree cache events")

	// Connect events handler to SessionService for session title events
	sessionService.SetEventsHandler(eventsHandler)
	log.Printf("✅ EventsHandler connected to SessionService for session title events")

	// Connect SessionService to GitService for Claude activity state tracking
	gitService.SetSessionService(sessionService)
	log.Printf("✅ SessionService connected to GitService for Claude activity state tracking")

	// Connect ClaudeMonitorService to SessionService for real-time activity tracking
	sessionService.SetClaudeMonitor(claudeMonitor)
	log.Printf("✅ ClaudeMonitorService connected to SessionService for real-time activity tracking")

	// Register routes
	v1.Get("/pty", ptyHandler.HandleWebSocket)

	// Auth routes
	v1.Post("/auth/github/start", authHandler.StartGitHubAuth)
	v1.Get("/auth/github/status", authHandler.GetAuthStatus)
	v1.Post("/auth/github/reset", authHandler.ResetAuthState)

	// Upload routes
	v1.Post("/upload", uploadHandler.UploadFile)

	// Git routes
	v1.Post("/git/checkout/:org/:repo", gitHandler.CheckoutRepository)
	v1.Get("/git/status", gitHandler.GetStatus)
	v1.Get("/git/worktrees", gitHandler.ListWorktrees)
	v1.Delete("/git/worktrees/:id", gitHandler.DeleteWorktree)
	v1.Post("/git/worktrees/cleanup", gitHandler.CleanupMergedWorktrees)
	v1.Post("/git/worktrees/:id/sync", gitHandler.SyncWorktree)
	v1.Get("/git/worktrees/:id/sync/check", gitHandler.CheckSyncConflicts)
	v1.Post("/git/worktrees/:id/merge", gitHandler.MergeWorktreeToMain)
	v1.Get("/git/worktrees/:id/merge/check", gitHandler.CheckMergeConflicts)
	v1.Get("/git/worktrees/:id/diff", gitHandler.GetWorktreeDiff)
	v1.Post("/git/worktrees/:id/preview", gitHandler.CreateWorktreePreview)
	v1.Post("/git/worktrees/:id/pr", gitHandler.CreatePullRequest)
	v1.Put("/git/worktrees/:id/pr", gitHandler.UpdatePullRequest)
	v1.Get("/git/worktrees/:id/pr", gitHandler.GetPullRequestInfo)
	v1.Post("/git/worktrees/:id/graduate", gitHandler.GraduateBranch)
	v1.Post("/git/worktrees/:id/refresh", gitHandler.RefreshWorktreeStatus)
	v1.Get("/git/github/repos", gitHandler.ListGitHubRepositories)
	v1.Get("/git/branches/:repo_id", gitHandler.GetRepositoryBranches)
	v1.Post("/git/template", gitHandler.CreateFromTemplate)

	// Claude routes
	v1.Get("/claude/session", claudeHandler.GetWorktreeSessionSummary)
	v1.Get("/claude/session/:uuid", claudeHandler.GetSessionByUUID)
	v1.Get("/claude/sessions", claudeHandler.GetAllWorktreeSessionSummaries)
	v1.Get("/claude/todos", claudeHandler.GetWorktreeTodos)
	v1.Post("/claude/messages", claudeHandler.CreateCompletion)
	v1.Get("/claude/settings", claudeHandler.GetClaudeSettings)
	v1.Put("/claude/settings", claudeHandler.UpdateClaudeSettings)

	// Session management routes
	v1.Get("/sessions/active", sessionHandler.GetActiveSessions)
	v1.Get("/sessions", sessionHandler.GetAllSessions)
	v1.Get("/sessions/workspace/:workspace", sessionHandler.GetSessionByWorkspace)
	v1.Get("/sessions/workspace/:workspace/session/:sessionId", sessionHandler.GetSessionById)
	v1.Delete("/sessions/workspace/:workspace", sessionHandler.DeleteSession)

	// Port monitoring routes
	v1.Get("/ports", portsHandler.GetPorts)
	v1.Get("/ports/:port", portsHandler.GetPortInfo)

	// Server info route
	v1.Get("/info", func(c *fiber.Ctx) error {
		commit, date, builtBy := GetBuildInfo()
		return c.JSON(fiber.Map{
			"version": GetVersion(),
			"build": fiber.Map{
				"commit":  commit,
				"date":    date,
				"builtBy": builtBy,
			},
		})
	})

	// Events routes
	v1.Get("/events", eventsHandler.HandleSSE)

	// Proxy routes for detected services (must be before dev middleware)
	// Will validate port numbers in handler and call Next() if invalid
	app.Get("/:port", proxyHandler.ProxyToPort)
	app.Get("/:port/*", proxyHandler.ProxyToPort)

	// Handle static files and SPA routing
	if handlers.IsDevMode() {
		// In development mode, proxy to Vite dev server
		log.Println("🔧 Development mode: proxying to Vite dev server", handlers.ViteServerURL())
		app.Use(func(c *fiber.Ctx) error {
			// Skip API routes and health/swagger
			path := c.Path()
			if path == "/health" ||
				strings.HasPrefix(path, "/swagger") ||
				strings.HasPrefix(path, "/v1/") {
				return c.Next()
			}
			// Port proxy routes are handled above with regex constraints
			// Proxy everything else to Vite
			return handlers.ProxyToVite(c)
		})
	} else {
		// Production mode: serve embedded static files or fallback to external
		if handlers.HasEmbeddedAssets() {
			log.Println("🚀 Production mode: serving embedded frontend assets")

			// Serve embedded static files
			app.Use("/", handlers.ServeEmbeddedAssets())

			// Fallback to index.html for SPA routing (embedded)
			app.Get("/*", handlers.ServeEmbeddedSPA)
		} else {
			// Fallback to external static files if assets not embedded
			log.Println("⚠️  Production mode: frontend assets not embedded, serving from ./dist")
			staticPath := os.Getenv("STATIC_PATH")
			if staticPath == "" {
				staticPath = "./dist"
			}

			app.Static("/", staticPath)

			// Fallback to index.html for SPA routing
			app.Get("/*", func(c *fiber.Ctx) error {
				return c.SendFile(staticPath + "/index.html")
			})
		}
	}

	// Get port from flag or environment variable
	port, _ := cmd.Flags().GetString("port")
	if envPort := os.Getenv("PORT"); envPort != "" {
		port = envPort
	}

	log.Printf("🚀 Catnip server starting on port %s", port)
	log.Fatal(app.Listen(":" + port))
}
