//
//  PreviewHelper.swift
//  catnip
//
//  Helper to load PTY captures for previews
//  Captures are generated using: container/cmd/capture-pty
//

import Foundation

#if DEBUG
extension MockPTYDataSource {
    // Load a PTY capture file generated by the Go capture-pty tool
    // To create new captures: cd container && ./capture-pty -output my-capture.json
    static func createPreviewDataSource(playbackSpeed: Double = 1.0) -> MockPTYDataSource {
        do {
            // Use the real captured PTY data
            return try MockPTYDataSource(captureFile: "pty-capture", playbackSpeed: playbackSpeed)
        } catch {
            NSLog("⚠️ Failed to load pty-capture.json, using fallback: %@", error.localizedDescription)

            // Fallback to simple mock data if capture file is missing
            let events = [
                CaptureEvent(timestampMs: 0, data: Data([0x1B, 0x5B, 0x32, 0x4A, 0x1B, 0x5B, 0x48])),
                CaptureEvent(timestampMs: 100, data: """
                    \u{1B}[1;36mClaude Code\u{1B}[0m is your AI pair programmer.

                    \u{1B}[32m> \u{1B}[0m\u{1B}[2mTry \"help me fix this bug\"\u{1B}[0m
                    """.data(using: .utf8)!),
            ]

            let metadata = CaptureMetadata(
                captureDate: Date(),
                totalBytes: events.reduce(0) { $0 + $1.data.count },
                durationSeconds: 0.5,
                events: events
            )

            return MockPTYDataSource(metadata: metadata, playbackSpeed: playbackSpeed)
        }
    }
}
#endif
