// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionDesktopService wraps the existing Session service for Wails exposure
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../catnip/internal/models/models.js";

/**
 * GetActiveSession gets current active session
 * @param {string} workspaceDir
 * @returns {$CancellablePromise<[any, boolean]>}
 */
export function GetActiveSession(workspaceDir) {
    return $Call.ByID(2719670191, workspaceDir);
}

/**
 * GetClaudeActivityState gets Claude activity state for a directory
 * @param {string} workDir
 * @returns {$CancellablePromise<models$0.ClaudeActivityState>}
 */
export function GetClaudeActivityState(workDir) {
    return $Call.ByID(1651454485, workDir);
}

/**
 * StartActiveSession starts an active session
 * @param {string} workspaceDir
 * @param {string} claudeSessionUUID
 * @returns {$CancellablePromise<void>}
 */
export function StartActiveSession(workspaceDir, claudeSessionUUID) {
    return $Call.ByID(1395651823, workspaceDir, claudeSessionUUID);
}

/**
 * UpdateSessionTitle updates session title
 * @param {string} workspaceDir
 * @param {string} title
 * @param {string} commitHash
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSessionTitle(workspaceDir, title, commitHash) {
    return $Call.ByID(2074346314, workspaceDir, title, commitHash);
}
