// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsDesktopService manages desktop-specific settings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAppInfo gets basic app information
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetAppInfo() {
    return $Call.ByID(2306012905).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAppSettings gets current desktop app settings
 * @returns {$CancellablePromise<$models.AppSettings | null>}
 */
export function GetAppSettings() {
    return $Call.ByID(1021663132).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateAppSettings updates desktop app settings
 * @param {$models.AppSettings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAppSettings(settings) {
    return $Call.ByID(3430225039, settings);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.AppSettings.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
