/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GitRouteImport } from './routes/git'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalIndexRouteImport } from './routes/terminal.index'
import { Route as TerminalSessionIdRouteImport } from './routes/terminal.$sessionId'
import { Route as GhSplatRouteImport } from './routes/gh.$'

const GitRoute = GitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/terminal/',
  path: '/terminal/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalSessionIdRoute = TerminalSessionIdRouteImport.update({
  id: '/terminal/$sessionId',
  path: '/terminal/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GhSplatRoute = GhSplatRouteImport.update({
  id: '/gh/$',
  path: '/gh/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/git': typeof GitRoute
  '/gh/$': typeof GhSplatRoute
  '/terminal/$sessionId': typeof TerminalSessionIdRoute
  '/terminal': typeof TerminalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/git': typeof GitRoute
  '/gh/$': typeof GhSplatRoute
  '/terminal/$sessionId': typeof TerminalSessionIdRoute
  '/terminal': typeof TerminalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/git': typeof GitRoute
  '/gh/$': typeof GhSplatRoute
  '/terminal/$sessionId': typeof TerminalSessionIdRoute
  '/terminal/': typeof TerminalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/git' | '/gh/$' | '/terminal/$sessionId' | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/git' | '/gh/$' | '/terminal/$sessionId' | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/git'
    | '/gh/$'
    | '/terminal/$sessionId'
    | '/terminal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GitRoute: typeof GitRoute
  GhSplatRoute: typeof GhSplatRoute
  TerminalSessionIdRoute: typeof TerminalSessionIdRoute
  TerminalIndexRoute: typeof TerminalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/git': {
      id: '/git'
      path: '/git'
      fullPath: '/git'
      preLoaderRoute: typeof GitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/': {
      id: '/terminal/'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/$sessionId': {
      id: '/terminal/$sessionId'
      path: '/terminal/$sessionId'
      fullPath: '/terminal/$sessionId'
      preLoaderRoute: typeof TerminalSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gh/$': {
      id: '/gh/$'
      path: '/gh/$'
      fullPath: '/gh/$'
      preLoaderRoute: typeof GhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GitRoute: GitRoute,
  GhSplatRoute: GhSplatRoute,
  TerminalSessionIdRoute: TerminalSessionIdRoute,
  TerminalIndexRoute: TerminalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
