name: Publish Dev Container Feature
on:
  push:
    branches: [ "main", "feature/codespaces" ]
    paths:
      - ".devcontainer/features/**"
      - ".github/workflows/publish-feature.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish devcontainer feature(s)
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1
        with:
          publish-features: "true"
          base-path-to-features: ".devcontainer/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}